@WebApi_HostAddress = http://localhost:5175
@WebApi_HostAddress_Prod = https://pwmgr.zqang.com

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

###

# GET TodoLists
GET {{WebApi_HostAddress}}/api/TodoLists

###
GET {{WebApi_HostAddress_Prod}}/api/Credential